services:
  healthystore:
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: healthyEcommerce
    networks:
      - HEALTHY

  test-db:
    image: mysql:8
    ports:
      - 3309:3309
    environment:
      MYSQL_ROOT_PASSWORD: testpass
      MYSQL_USER: halima
      MYSQL_PASSWORD: halima
      MYSQL_DATABASE: testdb
    networks:
      - HEALTHY

networks:
  HEALTHY:
    external: true
